import Head from 'next/head';
import Banner from '../components/Banner';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jiil Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex-auto h-screen w-screen bg-slate-100 m-auto bg-gradient-to-tr overflow-hidden ">
        <Banner />
      </div>
    </div>
  );
}
