import Head from 'next/head';
import Banner from '../components/Banner';
import Header from '../components/Header';
import MySkills from '../components/MySkills';
import WebDesign from '../components/WebDesign';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Jiil Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative  flex flex-col items-center">
        <Banner />
        <WebDesign />
        <MySkills />
      </main>
    </div>
  );
}
